PHONE_TO_LETTER = {
    'aɪ': 'i',
    'aʊ': 'ou',
    'b': 'b',
    'd': 'd',
    'dʒ': 'j',
    'eɪ': 'a',
    'f': 'f',
    'h': 'h',
    'iː': 'ee',
    'j': 'y',
    'k': 'c',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'oʊ': 'oa',
    'p': 'p',
    's': 's',
     't': 't',
    'tʃ': 'ch',
    'uː': 'u',
    'v': 'v',
    'w': 'w',
    'z': 's',
    'æ': 'a',
    'ð': 'th',
    'ŋ': 'ng',
    'ɑ': 'o',
    'ɔ': 'a',
    'ɔɪ': 'oi',
    'ə': 'a',
    'ɛ': 'e',
    'ɜː': 'ur',
    'ɡ': 'g',
    'ɪ': 'i',
    'ɹ': 'r',
    'ʃ': 'sh',
    'ʊ': 'o',
    'ʌ': 'u',
    'ʒ': 's',
    'θ': 'th'
}


def letterize(word):
    return ''.join([PHONE_TO_LETTER[phone] for phone in word.split(' ')])